joy_teleop:
  ros__parameters:
    move:
      type: topic
      interface_type: geometry_msgs/msg/TwistStamped
      topic_name: my_robot_controller/cmd_vel
      deadman_buttons: [5]
      axis_mappings:
        twist-linear-x:
          axis: 1
          scale: 0.05
          offset: 0.0
        twist-angular-z:
          axis: 0
          scale: 0.005
          offset: 0.0